[tools]
node = "20.18.1"
npm = "latest"
pnpm = "latest"

[env]
NODE_ENV = "development"

[tasks.dev]
description = "Start development server"
run = "npm run dev"

[tasks.build]
description = "Build for production"
run = "npm run build"

[tasks.preview]
description = "Preview production build"
run = "npm run preview"

[tasks.install]
description = "Install dependencies"
run = "npm install"

[tasks.deploy]
description = "Deploy to Cloudflare Pages"
run = "npm run deploy"